routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Admin Group
Route::group(array('prefix' => 'coulisses', 'middleware' => ['auth']), function () {

  Route::resource('user', 'UserController', ['except' => ['show']]);
  
  Route::get('filemanager', 'PageController@filemanager')->name('filemanager');

  Route::get('pages', 'PageController@index')->name('page.index');
  Route::get('newpage', 'PageController@create')->name('page.create');
  Route::post('storepage', 'PageController@store')->name('page.store');
  Route::get('editpage/{page_id}', 'PageController@edit')->name('page.edit');
  Route::post('updatepage/{page_id}', 'PageController@update')->name('page.update');
  Route::delete('destroypage/{id}', 'PageController@destroy')->name('page.destroy');
  Route::post('publicationpage/{id}', 'PageController@switchPublication');

  Route::resource('type', 'TypeController', ['except' => ['show']]);//->middleware('authAsMaintainer')
  Route::put('type-field/{type_id}', 'TypeController@updateField');
  Route::get('insert-type/{type_name}', 'TypeController@showInsertForm')->name('type.insertform');
  Route::get('insert-type/{type_name}/{rubrique_id}', 'TypeController@editInsertForm')->name('type.editInsert');
  Route::post('insert-type/{type_id}', 'TypeController@insertType')->name('type.insert');
  Route::get('inserted-type-index/{type_id}', 'TypeController@insertedTypeIndex')->name('type.insertedIndex');
  Route::post('insert-type/{type_id}/{rubrique_id}', 'TypeController@updateInsertedType')->name('type.insertUpdate');
  Route::post('destroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->middleware('ajax');
  Route::get('getdestroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->name('type.destroyInsert');
  Route::get('get-galleries', 'TypeController@getGalleries')->middleware('ajax');
  Route::post('publicationcontent/{id}', 'TypeController@switchPublication')->middleware('ajax');
  Route::post('archivecontent/{id}', 'TypeController@switchArchivage')->middleware('ajax');
  Route::post('sorttyperubriques/{type_id}', 'TypeController@sortTypeRubriques')->middleware('ajax');

  Route::resource('categorie', 'CategorieController', ['except' => ['create']]);
  Route::post('categorie/{id}/detach', 'CategorieController@detach')->middleware('ajax');
  Route::post('categorie/{type_id}/attach', 'CategorieController@attach')->middleware('ajax');
  Route::post('categorie_suggest/{type_id}', 'CategorieController@suggest')->middleware('ajax');

  Route::post('bloc/{id}', 'BlocController@update');
  Route::post('destroybloc/{id}', 'BlocController@destroy');
  Route::get('partial_bloc/{id}', 'BlocController@partialShow');
  Route::get('partial_drag/{id}', 'BlocController@partialShowDrag');
  Route::post('list-galleries', 'BlocController@listGalleries')->middleware('ajax');
  Route::post('search', 'BlocController@search')->name('bloc.search');

  Route::get('rubriques/{page_id}', 'RubriqueController@index')->name('rubrique.index');
  Route::post('rubrique/{id}', 'RubriqueController@update');
  Route::post('destroyrubrique/{id}', 'RubriqueController@destroy');
  Route::post('cols/{id}', 'RubriqueController@colsChange');
  Route::post('newrubrique/{id}', 'RubriqueController@newRubrique');
  Route::get('partial/coulisses/rubrique/{id}', 'RubriqueController@partialShow');
  Route::post('ascdesc/{id}', 'RubriqueController@switchOrder');
  Route::post('moveblock/{id}', 'RubriqueController@moveBlock');
  Route::post('change-type-content/{id}', 'RubriqueController@changeTypeContents');
  Route::post('publicationrubrique/{id}', 'RubriqueController@switchPublication');
  Route::post('sortpagerubriques/{page_id}', 'RubriqueController@sortRubriques');
  Route::post('updaterubriqueclass/{id}', 'RubriqueController@updateClass');
  
  Route::resource('mail', 'MailController');

  //Route::post('redactorimgupload', 'RedactorController@uploadImage');
  //Route::get('imagemanager', 'RedactorController@imageManager');
  Route::post('get-gallery', 'RedactorController@getGallery');
  
  Route::get('', 'PageController@goHome');
  Route::get('{page_title}', 'PageController@show')->name('back_page.show')->middleware('authAsAdmin');
});

Route::get('rgpd-notice', function () {
  return response('ok', 200)->cookie('no_rgpd', 'ok', 43200);
})->middleware('web');
Route::post('mail', 'PageController@mailFromContact')->name('page.mail');
Route::get('get-type-contents/{type}', 'RubriqueController@getTypeContents');
Route::get('{type}/{id_rubrique}/{title?}', 'RubriqueController@showTypeContentPage')->name('type_content');

/*
Route::get('testdrop', function (){
    return view('back.testdrop');
});
 */
Route::get('/', 'PageController@goHome')->name('page.home');
Route::get('/home', function () { return redirect()->route('page.home'); });

Route::get('/{page_title}', 'PageController@show')->name('page.show');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function pages()
    {
        return $this->hasMany('App\Models\Page');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

use App\Http\Requests\UserUpdateRequest;

use App\Repositories\UserRepository;
use App\Repositories\FooterRepository;
use App\Repositories\MenusRepository;
use App\Repositories\ControlRepository;
use App\Models\Page;
use App\Models\User;

class UserController extends Controller
{

    public function __construct(UserRepository $userRepository, FooterRepository $footerRepository, MenusRepository $menusRepository, ControlRepository $controlRepository)
    {
      $this->userRepository = $userRepository;
      $this->footerRepository = $footerRepository;
      $this->menusRepository = $menusRepository;
      $this->middleware('auth');
      $this->middleware('authAsAdmin');
      $this->nbrPerPage = $controlRepository->nbrPerPage;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $operation = 'index';
        $menus = $this->menusRepository->makeAdminMenus();
        $footer = $this->footerRepository->makeFooter();
        $users = $this->userRepository->getPaginate($this->nbrPerPage);
        $links = $users->render();

        return view('common.user.index', compact('users', 'links', 'menus', 'operation', 'footer'));
    }

    /**
     * Show the form for creating the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $operation = 'create';
        $title_tag = 'Ajouter un utilisateur';
        $menus = $this->menusRepository->makeAdminMenus();
        $footer = $this->footerRepository->makeFooter();

        return view('common.auth.register', compact( 'title_tag', 'menus', 'operation', 'footer'));
    }

    public function store(UserUpdateRequest $request) {
     
     //return redirect()->action('Auth\RegisterController@register');

      $inputs = array_merge($request->except(['password']), [
        'password' => Hash::make( $request->password ),
      ]);

     User::create($inputs);

     return redirect()->route('user.index')->with('info', 'l\'utilisateur est enregistré.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $operation = 'edit';
        $menus = $this->menusRepository->makeAdminMenus();
        $footer = $this->footerRepository->makeFooter();
        $user = $this->userRepository->getById($id);

        return view('common.user.edit',  compact('user', 'menus', 'operation', 'footer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, $id)
    {
      if($this->userRepository->isLastAdmin($id) && $this->userRepository->roleChange($id, $request->input('role'))){
        return redirect()->route('user.index')->withError("Vous ne pouvez pas supprimer le dernier administrateur.");
      }else{
        if($request->password != null){

          $inputs = array_merge($request->except(['password']), [
            'password' => Hash::make( $request->password ),
          ]);

        }else{
          $inputs = $request->except(['password']);
        }
        $this->userRepository->update($id, $inputs);
        return redirect()->route('user.index')->withInfo("L'utilisateur " . $request->input('name') . " a été modifié.");
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      if($this->userRepository->isLastAdmin($id)){
        return redirect()->route('user.index')->withError("Vous ne pouvez pas supprimer le dernier administrateur.");
      }else{
        $this->userRepository->destroy($id);
        return redirect()->route('user.index')->withInfo("L'utilisateur est supprimé");
      }
    }
}

resources/views/common/user/edit.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Compte de {!! $user->name !!}</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="col-12 col-lg-8 col-xl-6">
      <div class="card"> 
        <div class="card-header">
          <h3 class="card-title">Compte de {!! $user->name !!}</h3>
        </div>
        <div class="card-body"> 
          <form method="POST" action="{{ route('user.update', $user->id) }}" accept-charset="UTF-8">
            <input name="_method" type="hidden" value="put">
            <input name="_token" type="hidden" value="{{ csrf_token() }}">
            <div class="form-row">
              <div class="col-3 col-form-label text-md-right">
                <label for="name">Nom :</label>
              </div>
              <div class="col-9 form-group">
                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="Nom" name="name" type="text" value="{{ $user->name }}">
                {!! $errors->first('name', '<small class="invalid-feedback">:message</small>') !!}
              </div>
            </div>
            <div class="form-row">
              <div class="col-3 col-form-label text-md-right">
                <label for="username">Pseudo :</label>
              </div>
              <div class="col-9 form-group">
                <input class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" placeholder="Pseudo" name="username" type="text" value="{{ $user->username }}">
                {!! $errors->first('username', '<small class="invalid-feedback">:message</small>') !!}
              </div>
            </div>
            <div class="form-row">
              <div class="col-3 col-form-label text-md-right">
                <label for="email">E-mail :</label>
              </div>
              <div class="col-9 form-group">
                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="Email" name="email" type="email" value="{{ $user->email }}" id="email">
                {!! $errors->first('email', '<small class="invalid-feedback">:message</small>') !!}
              </div>
            </div>
            <div class="form-row">
              <div class="col-3 col-form-label text-md-right">
                <label for="role">Droits :</label>
              </div>
              <div class="col-9 form-group">
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="role" value="user"{{ $user->role == 'user' ? 'checked' : '' }}/>
                  <label class="form-check-label">Utilisateur</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="role" value="admin"{{ $user->role == 'admin' || $user->role == 'maintainer'? 'checked' : '' }}/>
                  <label class="form-check-label">Administrateur</label>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col-3 col-form-label text-md-right">
                <a class="pw-change" data-toggle="collapse" data-target="#passwords" aria-expanded="false" aria-controls="passwords">
                  Modifier le mot de passe <i class="fas fa-chevron-circle-down"></i>
                </a>
              </div>
            </div>
            <div class="collapse{{ $errors->has('password') ? ' show' : '' }}" id="passwords">
              <div class="form-row mt-2">
                <div class="col-3 col-form-label text-md-right">
                  <label for="password">Nouveau :</label>
                </div>
                <div class="col-9 form-group">
                  <input class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="Nouveau mot de passe" name="password" type="password" autocomplete="off">
                  {!! $errors->first('password', '<small class="invalid-feedback">:message</small>') !!}
                </div>
              </div>
              <div class="form-row">
                <div class="col-3 col-form-label text-md-right">
                  <label for="password_confirmation">Confirmer :</label>
                </div>
                <div class="col-9 form-group">
                  <input class="form-control" placeholder="Confirmer le mot de passe" name="password_confirmation" type="password">
                </div>
              </div>
            </div>
            <div class="form-row justify-content-between last">
              <input class="btn btn-info" type="submit" value="Envoyer">
              <a href="javascript:history.back()" class="btn btn-primary">
                <i class="fas fa-redo"></i> Retour
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
  <script src="/js/lists.js"></script>
@endsection

resources/views/common/user/index.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Utilisateurs</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Liste des utilisateurs</h3>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Nom</th>
                <th>E-Mail</th>
                <th>Pseudo</th>
                <th>Droits</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @foreach ($users as $user)
                <tr>
                  <td class="text-primary"><strong>{!! $user->name !!}</strong></td>
                  <td class="text-primary"><strong>{!! $user->email !!}</strong></td>
                  <td class="text-primary"><strong>{!! $user->username !!}</strong></td>
                  <td class="text-primary"><strong>{!! $user->role !!}</strong></td>
                  <td>
                    {{--@if(Auth::user()->role == 'admin')--}}
                      <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning"><i class="far fa-edit"></i><span class="sr-only"> Modifier</span></a>
                    {{--@endif--}}
                  </td>
                  <td>
                    {{--@if(Auth::user()->role == 'admin')--}}
                      <form method="POST" action="{{ route('user.destroy', $user->id) }}" accept-charset="UTF-8">
                        <input name="_method" type="hidden" value="DELETE">
                        <input name="_token" type="hidden" value="{{ csrf_token() }}">
                      
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Vraiment supprimer cet utilisateur ?')"><i class="fas fa-trash-alt"></i><span class="sr-only"> Supprimer</span></button>
                      </form>
                    {{--@endif--}}
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          {!! $links !!}
          <div class="row justify-content-between px-3">
            {{--@if(Auth::user()->role == 'admin')--}}
              <a href="{{ route('user.create') }}" class="btn btn-info">Ajouter un utilisateur</a>
            {{--@endif--}}
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-end">
          <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
        </div>
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
@endsection