routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Admin Group
Route::group(array('prefix' => 'coulisses', 'middleware' => ['auth']), function () {

  Route::resource('user', 'UserController', ['except' => ['show']]);
  
  Route::get('filemanager', 'PageController@filemanager')->name('filemanager');

  Route::get('pages', 'PageController@index')->name('page.index');
  Route::get('newpage', 'PageController@create')->name('page.create');
  Route::post('storepage', 'PageController@store')->name('page.store');
  Route::get('editpage/{page_id}', 'PageController@edit')->name('page.edit');
  Route::post('updatepage/{page_id}', 'PageController@update')->name('page.update');
  Route::delete('destroypage/{id}', 'PageController@destroy')->name('page.destroy');
  Route::post('publicationpage/{id}', 'PageController@switchPublication');

  Route::resource('type', 'TypeController', ['except' => ['show']]);//->middleware('authAsMaintainer')
  Route::put('type-field/{type_id}', 'TypeController@updateField');
  Route::get('insert-type/{type_name}', 'TypeController@showInsertForm')->name('type.insertform');
  Route::get('insert-type/{type_name}/{rubrique_id}', 'TypeController@editInsertForm')->name('type.editInsert');
  Route::post('insert-type/{type_id}', 'TypeController@insertType')->name('type.insert');
  Route::get('inserted-type-index/{type_id}', 'TypeController@insertedTypeIndex')->name('type.insertedIndex');
  Route::post('insert-type/{type_id}/{rubrique_id}', 'TypeController@updateInsertedType')->name('type.insertUpdate');
  Route::post('destroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->middleware('ajax');
  Route::get('getdestroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->name('type.destroyInsert');
  Route::get('get-galleries', 'TypeController@getGalleries')->middleware('ajax');
  Route::post('publicationcontent/{id}', 'TypeController@switchPublication')->middleware('ajax');
  Route::post('archivecontent/{id}', 'TypeController@switchArchivage')->middleware('ajax');
  Route::post('sorttyperubriques/{type_id}', 'TypeController@sortTypeRubriques')->middleware('ajax');

  Route::resource('categorie', 'CategorieController', ['except' => ['create']]);
  Route::post('categorie/{id}/detach', 'CategorieController@detach')->middleware('ajax');
  Route::post('categorie/{type_id}/attach', 'CategorieController@attach')->middleware('ajax');
  Route::post('categorie_suggest/{type_id}', 'CategorieController@suggest')->middleware('ajax');

  Route::post('bloc/{id}', 'BlocController@update');
  Route::post('destroybloc/{id}', 'BlocController@destroy');
  Route::get('partial_bloc/{id}', 'BlocController@partialShow');
  Route::get('partial_drag/{id}', 'BlocController@partialShowDrag');
  Route::post('list-galleries', 'BlocController@listGalleries')->middleware('ajax');
  Route::post('search', 'BlocController@search')->name('bloc.search');

  Route::get('rubriques/{page_id}', 'RubriqueController@index')->name('rubrique.index');
  Route::post('rubrique/{id}', 'RubriqueController@update');
  Route::post('destroyrubrique/{id}', 'RubriqueController@destroy');
  Route::post('cols/{id}', 'RubriqueController@colsChange');
  Route::post('newrubrique/{id}', 'RubriqueController@newRubrique');
  Route::get('partial/coulisses/rubrique/{id}', 'RubriqueController@partialShow');
  Route::post('ascdesc/{id}', 'RubriqueController@switchOrder');
  Route::post('moveblock/{id}', 'RubriqueController@moveBlock');
  Route::post('change-type-content/{id}', 'RubriqueController@changeTypeContents');
  Route::post('publicationrubrique/{id}', 'RubriqueController@switchPublication');
  Route::post('sortpagerubriques/{page_id}', 'RubriqueController@sortRubriques');
  Route::post('updaterubriqueclass/{id}', 'RubriqueController@updateClass');
  
  Route::resource('mail', 'MailController');

  //Route::post('redactorimgupload', 'RedactorController@uploadImage');
  //Route::get('imagemanager', 'RedactorController@imageManager');
  Route::post('get-gallery', 'RedactorController@getGallery');
  
  Route::get('', 'PageController@goHome');
  Route::get('{page_title}', 'PageController@show')->name('back_page.show')->middleware('authAsAdmin');
});

Route::get('rgpd-notice', function () {
  return response('ok', 200)->cookie('no_rgpd', 'ok', 43200);
})->middleware('web');
Route::post('mail', 'PageController@mailFromContact')->name('page.mail');
Route::get('get-type-contents/{type}', 'RubriqueController@getTypeContents');
Route::get('{type}/{id_rubrique}/{title?}', 'RubriqueController@showTypeContentPage')->name('type_content');

/*
Route::get('testdrop', function (){
    return view('back.testdrop');
});
 */
Route::get('/', 'PageController@goHome')->name('page.home');
Route::get('/home', function () { return redirect()->route('page.home'); });

Route::get('/{page_title}', 'PageController@show')->name('page.show');

resources/views/common/back/inc/aside_insert_type_card.blade.php
<div class="card-header">
  <h4>Catégories</h4>
</div>
<br/>
<div class="card-body"> 
  @if($type->categories()->count() > 0)
    <div class="form-group" id="categories-checkbox">
      @foreach($type->categories as $categorie)
        <div class="form-check">
          <input type="checkbox" name="categorie{{ $categorie->id }}" value="{{ $categorie->id }}" {{ isset($type_content) && in_array($categorie->id, $categories_ids) ? 'checked' : '' }} />
          <label for="{{ $categorie->id }}">{{ $categorie->name }}</label><br />
        </div>
      @endforeach
    </div>
  @endif
  <div class="d-flex justify-content-between">
    <button class="btn btn-info" name="submitbutton" type="submit" value="save"><i class="far fa-save"></i>{{ isset($type_content) ? ' Modifier' : ' Insérer'}}</button>
    @if(isset($type_content))
      <button class="btn btn-warning" name="submitbutton" type="submit" value="copy"><i class="far fa-copy"></i> Dupliquer</button>
      <a class="btn btn-danger" href="{{ route('type.destroyInsert', $type_content->id) }}" ><i class="far fa-trash-alt"></i> Supprimer</a>
    @endif
  </div>
  </form>
</div>
<div class="card-footer d-flex justify-content-between">
  <a href="javascript:history.back()" class="btn btn-primary btn-sm">
    <i class="fa fa-redo"></i> Retour
  </a>
  <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
</div>

resources/views/common/back/inc/aside_type_card.blade.php
<div class="card-header">
  <p>Type de contenu : {{ $type->content_type }}</p>
  <h4>Catégories</h4>
</div>
<br/>
<div class="card-body"> 

  <div class="form-group" id="categories-container">
    @if($type->categories()->count() > 0)
      @include('common.back.inc.categorie_table')
    @endif
  </div>
  <div class="form-group">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalCategorie">
      Créer une catégorie
    </button>
  </div>
  <div class="form-group">
    <label for="choose_cat" class="control-label">Attacher une catégorie existante :</label>
    <input class="form-control" placeholder="Chercher..." name="choose_cat" type="text">
  </div>

  <div class="d-flex justify-content-between">
    <button class="btn btn-info" type="submit"><i class="far fa-save"></i> {{ 'Modifier' }}</button>
    <a href="javascript:history.back()" class="btn btn-primary">
      <i class="fa fa-redo"></i> Retour
    </a>
  </div>
  </form>
</div>
<div class="card-footer d-flex justify-content-end">
  <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
</div>

<!-- Modal -->
<div class="modal fade" id="modalCategorie" tabindex="-1" role="dialog" aria-labelledby="modalCategorieTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="title-ajout" >
          Ajouter une catégorie
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="name" class="control-label">Nom</label>
          <input class="form-control" name="name" type="text" id="name">
          <small class="invalid-feedback"></small>
          <input class="d-none" name="type_id" type="number" value="{{ $type->id }}">
        </div>
      </div>
      <div class="modal-footer">
        <button id="ajout-categorie" type="button" class="btn btn-primary"><i class="far fa-save"></i> Enregistrer</button>
      </div>
    </div>
  </div>
</div>

resources/views/common/back/inc/categorie_table.blade.php
<table class="table" route="categorie">
  <thead>
    <tr>
      <th>Titre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach($type->categories as $categorie)
      <tr>
        <td class="titre">{!! $categorie->name !!}</td>
        <td>
          <button type="button" data-id="{{ $categorie->id }}" class="btn btn-outline-primary btn-sm categorieo" title="Modifier"><i class="fa fa-pen-square"></i> <span class="sr-only">Modifier</span></button>
        </td>
        <td>
          <button type="button" data-id="{{ $categorie->id }}" class="btn btn-outline-danger btn-sm categoried" title="Détacher"><i class="fa fa-cut"></i> <span class="sr-only">Détacher</span></button>
        </td>
        <td>
          <button type="button" data-id="{{ $categorie->id }}" class="btn btn-outline-danger btn-sm categoriex" title="Supprimer"><i class="fa fa-trash"></i> <span class="sr-only">Supprimer</span></button>
        </td>
      </tr>
    @endforeach
  </tbody>
</table>

resources/views/common/back/inc/edit_mail.blade.php
<div class="card-header"><h3>Modifier {{ $mail->email }}</h3></div>
<br/>
<div class="card-body"> 
  {!! Form::open(array('route' => ['mail.update', $mail->id], 'method' => 'PUT')) !!}
  <div class="form-row">
    <div class="col-3 col-form-label text-md-right">
      {{ Form::label('password', 'Nouveau mot de passe :' ) }}
    </div>
    <div class="col-9 input-group">
      {!! Form::password('password', ['class' => 'form-control' . ( $errors->has('password') ? ' is-invalid' : '' ), 'placeholder' => 'Nouveau mot de passe'] ) !!}
      {!! $errors->first('password', '<small class="invalid-feedback">:message</small>') !!}
    </div>
  </div>
  <div class="form-row">
    <div class="col-3 col-form-label text-md-right">
      {{ Form::label('password_confirmation', 'Confirmer :' ) }}
    </div>
    <div class="col-9 input-group">
      {!! Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Confirmer le mot de passe']) !!}
    </div>
  </div>
  <div class="row justify-content-between px-3">
    {!! Form::submit('Modifier', ['class' => 'btn btn-info']) !!}
    <a href="javascript:history.back()" class="btn btn-primary">
      <i class="fa fa-redo"></i> Retour
    </a>
  </div>
  {!! Form::close() !!}
</div>

resources/views/common/back/inc/galleries.blade.php
<form id="gallery_form">
  <input type="hidden" name="_token" value="{{ csrf_token() }}" />
  <div class="form-row">
    <div class="form-group col-3">
      <div class="form-check">
        <input class="form-check-input" type="radio" name="round_border" value="0" checked>
        <label class="form-check-label" for="exampleRadios1">
          Carrés
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="round_border" value="1">
        <label class="form-check-label" for="exampleRadios1">
          Ronds
        </label>
      </div>
      <button type="button" class="btn btn-primary btn-sm" id="insert-gallery">Insérer <i class="fas fa-cog fa-spin fa-lg"></i></button>
    </div>
    <div class="form-group col-9">
      <select multiple class="form-control" name="gallery">
        @foreach($galleries as $key => $value)
          <option class="select-gallery" value="{{ $value }}">{{ $key }}</option>
        @endforeach
      </select>
    </div>
  </div>
</form>

resources/views/common/back/inc/insert_type.blade.php
@inject('module_control', 'ModuleControl')
@php
  $editing = isset($type_content) ? true : false;
@endphp

<div class="card-header"><h2>Insertion {{ $type->content_type }}</h2></div>
<br/>
<div class="card-body"> 
  <div class="form-row">
    <div class="form-group col-12 col-md-5">
      <button class="btn btn-primary btn-sm" type="button" id="add-gallery" aria-expanded="false" aria-controls="gallery-collapse"><i class="far fa-images"></i> Ajouter une galerie d'images</button>
    </div>
    <div class="collapse col-12 col-md-7" id="gallery-collapse">
      {{--ajax include galleries on click to show--}}
      @include('common.back.inc.galleries')
    </div>
  </div>
    @if($editing)
    <form method="POST" action="{{ route('type.insertUpdate', [$type->id, $type_content->id]) }}" accept-charset="UTF-8">
    @else
    <form method="POST" action="{{ route('type.insert', $type->id) }}" accept-charset="UTF-8">
    @endif
    <input name="_token" type="hidden" value="{{ csrf_token() }}">
  {{--{!! Form::open(array('route' => $editing ? ['type.insertUpdate', $type->id, $type_content->id] : ['type.insert', $type->id], 'method' => 'POST')) !!}--}}
  <div class="form-row">
    <div class="form-check col-12 col-md-6">
      <input type="checkbox" name="publie" value="1"{{ $editing && $type_content->publie ? ' checked' : '' }}/>
      <label for="publie"> Publié</label><br />
    </div>
    <div class="form-check col-12 col-md-6">
      <input type="checkbox" name="archive" value="1"{{ $editing && $type_content->archive ? ' checked' : '' }}/>
      <label for="archive"> Archivé</label><br />
    </div>
  </div>

  @if($type->child_of > 0)
    <div class="form-row">
      <div class="col-2 col-form-label">
        <label for="parent_id">Appartient à :</label>
        {{--{{ Form::label('parent_id', 'Appartient à :' ) }}--}}
      </div>
      <div class="col-10 form-group">
        @foreach($parent_type->rubriques as $parent)
          <div class="form-check">
            <input class="form-check-input" type="radio" name="parent_id" value="{{ $parent->id }}"{{ ($editing && $parent->id == $type_content->parent_id) ? 'checked' : '' }}/>
            <label class="form-check-label"> {!! strip_tags( $parent->blocs()->where('place', '1')->first()->contenu ) !!}</label>
          </div>
        @endforeach
      </div>
    </div>
  @endif

  <div class="form-group">
    <div class="form-row">
      <div class="input-group">
        <label class="control-label" for="rubrique_place">place :</label>
        <input name="rubrique_place" type="number" min="0" max="{{ $editing ? ( $total - 1 ) : $total }}" class="form-control col-12 col-lg-4 offset-lg-1{{ $errors->has('rubrique_place') ? ' is-invalid' : '' }}" value="{{ $editing ? $type_content->place : $total }}"/>
      </div>
    </div>
  </div>

  @for($i=0; $i<$nb_champs; $i++)
    @php
      $field = $json_fields->fields[$i];
      //in all cases, space must be replaced by _ in form name
      $field_name_error = preg_replace('/\s/', '_', $field->name);
      if($editing){
        $contenu = $module_control->getData($type_content, $field->name);
        if($field->type == "date" && !preg_match('/^\d{4}-\d{2}-\d{2}$/', $contenu)){
          $contenu = "2004-08-15";
        }elseif($field->type == "time" && !preg_match('/^\d{2}:\d{2}:\d{2}$/', $contenu)){
          $contenu = "12:00:00";
        }
        //elseif($field->type == "nb" && !preg_match('/^\d+$/', $contenu)){
        //  $contenu = 0;
        //}
      }
    @endphp
    @if($field->type == 'date')
      <div class="form-group">
        <div class="form-row">
          <label for="{{ $field->name }}" class="control-label col-12 col-lg-3">{{ $field->name . ' :' }}</label>
          {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label col-12 col-lg-3']) !!}--}}
          <div class="input-group date col-12 col-lg-4" id="datepicker{{ $i }}" data-target-input="nearest">
            <input type="text" name="{{ $field->name }}" class="form-control datetimepicker-input {{ $errors->has($field_name_error) ? ' is-invalid' : '' }}" value="{{ $editing ? date_format(date_create($contenu), 'd/m/Y') : old($field->name) }}"/>
            <div class="input-group-append" data-target="#datepicker{{ $i }}" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-calendar"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    @elseif($field->type == 'time')
      <div class="form-group">
        <div class="form-row">
          <label for="{{ $field->name }}" class="control-label col-12 col-lg-3">{{ $field->name . ' :' }}</label>
          {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label col-12 col-lg-3']) !!}--}}
          <div class="input-group heure col-12 col-lg-4" id="timepicker{{ $i }}" data-target-input="nearest">
            <input type="text" name="{{ $field->name }}" class="form-control datetimepicker-input {{ $errors->has($field_name_error) ? ' is-invalid' : '' }}" value="{{ $editing ? date_format(date_create($contenu), 'H:i') : old($field->name) }}"/>
            <div class="input-group-append" data-target="#timepicker{{ $i }}" data-toggle="datetimepicker">
              <div class="input-group-text"><i class="fa fa-clock"></i></div>
            </div>
          </div>
        </div>
      </div>
    @elseif($field->type == 'nb')
      <div class="form-group">
        <div class="form-row">
          <div class="input-group">
            <label for="{{ $field->name }}" class="control-label">{{ $field->name . ' :' }}</label>
            {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label']) !!}--}}
            <input type="number" step="0.01" name="{{ $field->name }}" class="form-control col-12 col-lg-4 offset-lg-1{{ $errors->has($field_name_error) ? ' is-invalid' : '' }}" value="{{ $editing ? $contenu : old($field->name) }}"/>
          </div>
        </div>
      </div>
    @elseif($field->type == 'text-raw')
      <div class="form-group">
        <div class="form-row">
          <div class="input-group">
            <label for="{{ $field->name }}" class="control-label">{{ $field->name . ' :' }}</label>
            {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label']) !!}--}}
            <input type="text" name="{{ $field->name }}" class="form-control col-12 col-lg-4 offset-lg-1{{ $errors->has($field_name_error) ? ' is-invalid' : '' }}" value="{{ $editing ? $contenu : old($field->name) }}"/>
          </div>
        </div>
      </div>
    @elseif($field->type == 'checkbox')
      <div class="form-group">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="{{ $field->name }}" value="1"{{ $editing && $contenu ? " checked" : "" }}>
          <label class="form-check-label" for="{{ $field->name }}">
            {{ $field->name }}
          </label>
        </div>
      </div>
    @elseif(preg_match('/titre/i', $field->name))
      <div class="form-group">
        <label for="{{ $field->name }}" class="control-label">{{ $field->name . ' :' }}</label>
        {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label']) !!}--}}
        <textarea name="{{ $field->name }}" class="form-control simple-redactored">{{ $editing ? $contenu : old($field->name) }}</textarea>
      </div>
    @elseif(preg_match('/image/i', $field->name))
      <div class="form-group">
        <label for="{{ $field->name }}" class="control-label">{{ $field->name . ' :' }}</label>
        {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label']) !!}--}}
        <textarea name="{{ $field->name }}" class="form-control image-redactored">{{ $editing ? $contenu : old($field->name) }}</textarea>
      </div>
    @else
      <div class="form-group">
        <label for="{{ $field->name }}" class="control-label">{{ $field->name . ' :' }}</label>
        {{--{!! Form::label($field->name, $field->name . ' :', ['class' => 'control-label']) !!}--}}
        <textarea name="{{ $field->name }}" class="form-control redactored">{{ $editing ? $contenu : old($field->name) }}</textarea>
      </div>
    @endif
  @endfor
</div>

resources/views/common/back/inc/menu_rubrique.blade.php
  <div class="dropdown cols-button">
    <button id="dropdownBlocsButton" type="button" class="dropdown-toggle btn btn-secondary btn-sm" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" >Organiser</button>

    <div class="dropdown-menu" aria-labelledby="dropdownBlocsButton">
      <a class="dropdown-item change-col" data-colonnes="1">1 colonne</a>
      <a class="dropdown-item change-col" data-colonnes="2">2 colonnes</a>
      <a class="dropdown-item change-col" data-colonnes="3">3 colonnes</a>
      <a class="dropdown-item ranger">actualiser</a>
      <a class="dropdown-item inverser">inverser</a>
      <a class="dropdown-item deplacer">déplacer</a>
    </div>
  </div>

  <div class="dropdown bloc-button">
    <button id="dropdownAddButton" type="button" class="dropdown-toggle btn btn-secondary btn-sm" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" >Ajouter</button>
    <div class="dropdown-menu" aria-labelledby="dropdownAddButton">
      <a class="dropdown-item add-bloc" data-format="large" data-order="{{ $order }}" >bloc large</a>
      <a class="dropdown-item add-bloc" data-format="normal" data-order="{{ $order }}" >bloc normal</a>
      @if(!isset($rubrique->type_contents))
        @foreach(App\Models\Type::where('available', 1)->get() as $type)
          <a class="dropdown-item change-type" data-contentType="{{ $type->content_type }}" data-dbAction="add">Les {{ $type->content_type }}s</a>
        @endforeach
      @else
        <a class="dropdown-item change-type" data-contentType="{{ $rubrique->inclusive_type['content_type'] }}" data-dbAction="remove">Retirer les<br>{{ $rubrique->inclusive_type['content_type'] }}s</a>
      @endif

      <div class="dropdown-item">
        <label for="gallery">Galerie d'images</label><br>
        <input name="gallery" type="text" class="select-gallery" placeholder="Entrer nom..." autocomplete="off" data-toggle="popover" data-content="error"/>
      </div>
    </div>
  </div>

resources/views/common/back/inc/sidebar.blade.php
<nav id="sidebar">
  <section id="fixed-sidebar">

    <button type="button" class="btn btn-secondary sidebarCollapse">
      <i class="fas fa-align-left"></i>
      <span>Admin</span>
    </button>

    <div class="sidebar-header">
      <h4>{{ Auth::user()->name }}</h4>
    </div>

    <ul class="list-unstyled components">
      @if(isset($page))
        <li>
          <a href="#submenu-page" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Page</a>
          <ul class="collapse list-unstyled" id="submenu-page">
            <li>
              <a href="{{ route('page.create') }}">Ajouter</a>
            </li>
            <li>
              <a href={{ route('page.edit', $page->id) }}">Modifier</a>
            </li>
            <li>
              <a id="destroy-page">Supprimer</a>
            </li>
            <li>
              <a id="publication">{{ $page->publie? "Masquer" : "Publier" }}</a>
            </li>
            @if(config('modules.multi_rubrique'))
              <li>
                <a href="{{ route('rubrique.index', $page->id) }}">Liste des rubriques</a>
              </li>
              <li>
                <a id="add-rubrique">Ajouter une rubrique</a>
              </li>
            @endif
            <li>
              <a href="{{ route('page.index') }}">Liste des pages</a>
            </li>
          </ul>
        </li>
      @else
        <li>
          <a href="{{ route('page.index') }}">Liste des pages</a>
        </li>
      @endif
      <li>
        <a href="#submenu-type" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Types de contenus</a>
        <ul class="collapse list-unstyled" id="submenu-type">
          <li>
            <a href="{{ route('type.create') }}">Créer</a>
          </li>
          <li>
            <a href="{{ route('type.index') }}">Voir les types de contenu</a>
          </li>
        </ul>
      </li>
      @php
        if(!isset($types)){
          $types = App\Models\Type::all();
        }
      @endphp
      @if($types->count()>0)
        <li>
          <a href="#subsubmenu-types" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Ajouter</a>
          <ul class="collapse list-unstyled" id="subsubmenu-types">
            @foreach($types as $type)
              <li>
                <a href="{{ route('type.insertform', $type->content_type) }}">{{ $type->content_type }}</a>
              </li>
            @endforeach
          </ul>
        </li>
        <li>
          <a href="#subsubmenu-insertedTypes" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Lister</a>
          <ul class="collapse list-unstyled" id="subsubmenu-insertedTypes">
            @foreach($types as $type)
              <li>
                <a href="{{ route('type.insertedIndex', $type->id) }}">{{ $type->content_type }}</a>
              </li>
            @endforeach
          </ul>
        </li>
      @endif
      <li>
        <a href='{{ route('user.index') }}'>
          <i class="fas fa-user-friends"></i> Utilisateurs
        </a>
      </li>
      <li>
        <a href='{{ route('user.edit', Auth::user()->id) }}'>
          <i class="fas fa-user-circle"></i> Compte
        </a>
      </li>
      <li>
        <a href="{{ route('filemanager') }}" target="_blank"><i class="fas fa-folder-open"></i> Gestionnaire de Fichiers</a>
      </li>
      @if(config('modules.mails') == true)
        <li>
          <a href='{{ route('mail.index') }}'>
            <i class="fas fa-at"></i> Gestion des Emails
          </a>
        </li>
      @endif
      <li>
        <a href="{{ route('logout') }}"
           onclick="event.preventDefault();
           document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt"></i> Déconnexion
        </a>
        <form method="POST" action="{{ route('logout') }}" accept-charset="UTF-8" id="logout-form" hidden="">
          <input name="_token" type="hidden" value="{{ csrf_token() }}">
        </form>
      </li>
      <li>
        <div class="sidebarCollapse chevron"><i class="fas fa-chevron-circle-left"></i></div>
      </li>
    </ul>
    
  </section>

</nav>