routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Admin Group
Route::group(array('prefix' => 'coulisses', 'middleware' => ['auth']), function () {

  Route::resource('user', 'UserController', ['except' => ['show']]);
  
  Route::get('filemanager', 'PageController@filemanager')->name('filemanager');

  Route::get('pages', 'PageController@index')->name('page.index');
  Route::get('newpage', 'PageController@create')->name('page.create');
  Route::post('storepage', 'PageController@store')->name('page.store');
  Route::get('editpage/{page_id}', 'PageController@edit')->name('page.edit');
  Route::post('updatepage/{page_id}', 'PageController@update')->name('page.update');
  Route::delete('destroypage/{id}', 'PageController@destroy')->name('page.destroy');
  Route::post('publicationpage/{id}', 'PageController@switchPublication');

  Route::resource('type', 'TypeController', ['except' => ['show']]);//->middleware('authAsMaintainer')
  Route::put('type-field/{type_id}', 'TypeController@updateField');
  Route::get('insert-type/{type_name}', 'TypeController@showInsertForm')->name('type.insertform');
  Route::get('insert-type/{type_name}/{rubrique_id}', 'TypeController@editInsertForm')->name('type.editInsert');
  Route::post('insert-type/{type_id}', 'TypeController@insertType')->name('type.insert');
  Route::get('inserted-type-index/{type_id}', 'TypeController@insertedTypeIndex')->name('type.insertedIndex');
  Route::post('insert-type/{type_id}/{rubrique_id}', 'TypeController@updateInsertedType')->name('type.insertUpdate');
  Route::post('destroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->middleware('ajax');
  Route::get('getdestroyinsertedrubrique/{id}', 'TypeController@destroyInsertedRubrique')->name('type.destroyInsert');
  Route::get('get-galleries', 'TypeController@getGalleries')->middleware('ajax');
  Route::post('publicationcontent/{id}', 'TypeController@switchPublication')->middleware('ajax');
  Route::post('archivecontent/{id}', 'TypeController@switchArchivage')->middleware('ajax');
  Route::post('sorttyperubriques/{type_id}', 'TypeController@sortTypeRubriques')->middleware('ajax');

  Route::resource('categorie', 'CategorieController', ['except' => ['create']]);
  Route::post('categorie/{id}/detach', 'CategorieController@detach')->middleware('ajax');
  Route::post('categorie/{type_id}/attach', 'CategorieController@attach')->middleware('ajax');
  Route::post('categorie_suggest/{type_id}', 'CategorieController@suggest')->middleware('ajax');

  Route::post('bloc/{id}', 'BlocController@update');
  Route::post('destroybloc/{id}', 'BlocController@destroy');
  Route::get('partial_bloc/{id}', 'BlocController@partialShow');
  Route::get('partial_drag/{id}', 'BlocController@partialShowDrag');
  Route::post('list-galleries', 'BlocController@listGalleries')->middleware('ajax');
  Route::post('search', 'BlocController@search')->name('bloc.search');

  Route::get('rubriques/{page_id}', 'RubriqueController@index')->name('rubrique.index');
  Route::post('rubrique/{id}', 'RubriqueController@update');
  Route::post('destroyrubrique/{id}', 'RubriqueController@destroy');
  Route::post('cols/{id}', 'RubriqueController@colsChange');
  Route::post('newrubrique/{id}', 'RubriqueController@newRubrique');
  Route::get('partial/coulisses/rubrique/{id}', 'RubriqueController@partialShow');
  Route::post('ascdesc/{id}', 'RubriqueController@switchOrder');
  Route::post('moveblock/{id}', 'RubriqueController@moveBlock');
  Route::post('change-type-content/{id}', 'RubriqueController@changeTypeContents');
  Route::post('publicationrubrique/{id}', 'RubriqueController@switchPublication');
  Route::post('sortpagerubriques/{page_id}', 'RubriqueController@sortRubriques');
  Route::post('updaterubriqueclass/{id}', 'RubriqueController@updateClass');
  
  Route::resource('mail', 'MailController');

  //Route::post('redactorimgupload', 'RedactorController@uploadImage');
  //Route::get('imagemanager', 'RedactorController@imageManager');
  Route::post('get-gallery', 'RedactorController@getGallery');
  
  Route::get('', 'PageController@goHome');
  Route::get('{page_title}', 'PageController@show')->name('back_page.show')->middleware('authAsAdmin');
});

Route::get('rgpd-notice', function () {
  return response('ok', 200)->cookie('no_rgpd', 'ok', 43200);
})->middleware('web');
Route::post('mail', 'PageController@mailFromContact')->name('page.mail');
Route::get('get-type-contents/{type}', 'RubriqueController@getTypeContents');
Route::get('{type}/{id_rubrique}/{title?}', 'RubriqueController@showTypeContentPage')->name('type_content');

/*
Route::get('testdrop', function (){
    return view('back.testdrop');
});
 */
Route::get('/', 'PageController@goHome')->name('page.home');
Route::get('/home', function () { return redirect()->route('page.home'); });

Route::get('/{page_title}', 'PageController@show')->name('page.show');

resources/views/common/back/email_contact.blade.php
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <ul>
      <li><strong>Nom de l'expéditeur</strong> : {!! $nom !!}</li>
      <li><strong>Email de l'expéditeur</strong> : <a href="mailto:{!! $email !!}">{!! $email !!}</a></li>
      <li><strong>Sujet</strong> : {!! $subject !!}</li>
    </ul>
    {!! $texte !!}
  </body>
</html>

resources/views/common/back/fileManager.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Gestionnaire de fichiers</title>
  <link href="/css/admin.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Gestionnaire de fichiers</h3>
        </div>
        <div class="card-body">
          <div class="fm-container">
            <div id="fm"></div>
          </div>
          <div class="card-footer d-flex justify-content-end mt-2">
            <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
          </div>
        </div>{{--card-body--}}
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
  <script src="/js/admin.js"></script>
  {{--<script src="/js/lists.js"></script>--}}
@endsection

resources/views/common/back/form.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>{{ $operation == 'create' ? 'Ajouter' : 'Modifier' }} {{ $model }}</title>
  <link href="/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet">
  <link href="/css/admin.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('vendor/file-manager/css/file-manager.css') }}">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="col-12 col-lg-8">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      @if(session()->has('errors'))
        @foreach($errors->all() as $error)
          <div class="alert alert-danger alert-dismissible">{!! $error !!}</div>
        @endforeach
      @endif
      <div class="card card-default">
        @if($model == 'page')
          @include('common.back.inc.new_page')
        @elseif($operation == 'insert' && $model == 'type')
          @include('common.back.inc.insert_type')
        @elseif($model == 'type')
          @include('common.back.inc.new_type')
        @elseif($model == 'mail')
          @if($operation == 'create')
            @include('common.back.inc.new_mail')
          @elseif($operation == 'edit')
            @include('common.back.inc.edit_mail')
          @endif
        @endif
        @if($model == 'page' || $operation == 'create')
          <div class="card-footer d-flex justify-content-end">
            <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
          </div>
        @endif
      </div>
    </div>
    @if($model == 'type' && $operation == 'edit')
      <div class="col-12 col-lg-4">
        <div class="card card-default">
          @include('common.back.inc.aside_type_card')
        </div>
      </div>
    @elseif($model == 'type' && $operation == 'insert')
      <div class="col-12 col-lg-4">
        <div class="card card-default">
          @include('common.back.inc.aside_insert_type_card')
        </div>
      </div>
    @endif
  </section>

@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="{{ asset('vendor/file-manager/js/file-manager.js') }}"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
  @if($operation == 'insert' && $model == 'type')
    <script src="/js/insert_form.js"></script>
  @endif
  @if($operation == 'edit' || $operation == 'create' && $model == 'type')
    <script src="/js/plugins/popover-suggest.js"></script>
    <script src="/js/categorie.js"></script>
    <script src="/js/fields.js"></script>
  @endif
@endsection

resources/views/common/back/insertedTypeIndex.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Index {{ $type->content_type }}</title>
  <link href="/css/admin.css" rel="stylesheet">
  <link rel="stylesheet" href="/tools/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="/tools/jquery_ui/jquery-ui.min.css">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')
          
  <section class='row center-card'>
    <div>
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card" id="typeList" data-typeid="{{$type->id}}">
        <div class="card-header">
          <h3 class="card-title w-50 d-inline-block">Liste du type : {{$type->content_type}}</h3>
          <form method="POST" action="{{ route('bloc.search') }}" class="w-50 float-right form-inline" accept-charset="UTF-8">
            <input name="_token" type="hidden" value="{{ csrf_token() }}">
            <div class="form-group mb-3">
              <input type="text" name="string" class="form-control border-secondary bg-transparent {{ $errors->has("string") ? ' is-invalid' : '' }}">
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary"><span class="icon-search"></span></button>
              </div>
              {!! $errors->first('string', '<small class="invalid-feedback">:message</small>') !!}
            </div>
            <div class="form-group ml-sm-2 mb-3">
              <label for="search-fields">dans le champ </label>
              <select name="field" class="form-control ml-2" id="search-fields">
                @foreach($json_fields as $field)
                  @if( !in_array(strtolower($field->name), ['image', 'photo']) )
                    <option>{{ $field->name }}</option>
                  @endif
                @endforeach
              </select>
            </div>
          </form>
          <p>Nombre total : {{$total}}</p>
        </div>
        <div class="card-body">

          <div id="index-container">
            @include('common.back.inc.insertedTypes-table')
          </div>
          <div class="row justify-content-between px-3">
              <a class="btn btn-info" href="{{ route('type.insertform', $type->content_type) }}">Ajouter {{ $type->content_type }}</a>
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-end">
          <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
        </div>
      </div>
    </div>
  </section>

@endsection

@section('scripts')
  <script src="/tools/jquery_ui/jquery-ui.min.js"></script>
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
  <script src="/js/lists.js"></script>
  <script src="/tools/fancybox/jquery.fancybox.min.js"></script>
@endsection

resources/views/common/back/mailIndex.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Emails</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="col-12 col-lg-8 col-xl-6">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Liste des mails</h3>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Email</th>
                <th></th>{{--modifier--}}
                <th></th>{{--supprimer--}}
              </tr>
            </thead>
            <tbody>
              @if($failed_connexion)
                <tr><td>Echec de la connexion.</td></tr>
              @else
                @foreach ($mails as $mail)
                  <tr>
                    <td class="text-primary">{!! $mail->email !!}</td>
                    <td>
                      <a class="btn btn-sm btn-success" href="{{ route('mail.show', [$mail->id]) }}" title="Voir les paramètres de connexion"><i class="far fa-eye"></i><span class="sr-only">voir</span></a>

                    </td>
                    <td>
                      <a href="{{ route('mail.edit', $mail->id) }}" class="btn btn-sm btn-warning" title="Modifier le mot de passe" ><i class="far fa-edit"></i><span class="sr-only"> Modifier</span></a>
                    </td>
                    <td>
                      {{-- Form::open(['method' => 'DELETE', 'route' => ['mail.destroy', $mail->id]]) --}}
                      <form method="POST" action="{{ route('mail.destroy', $mail->id) }}" accept-charset="UTF-8">
                        <input name="_method" type="hidden" value="DELETE">
                        <input name="_token" type="hidden" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Vraiment supprimer cet Email ?')"><i class="fas fa-trash-alt"></i><span class="sr-only"> Supprimer</span></button>
                      </form>
                    </td>
                  </tr>
                @endforeach
              @endif
            </tbody>
          </table>
          {!! $failed_connexion ? '' : $mails->links() !!}
          <div class="row justify-content-between px-3">
            <a href="{{ route('mail.create') }}" class="btn btn-info {{ $failed_connexion ? 'disabled' : '' }}">Ajouter un email</a>
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
          <div class="card-footer d-flex justify-content-end mt-2">
            <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
          </div>
        </div>{{--card-body--}}
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
  <script src="/js/lists.js"></script>
@endsection

resources/views/common/back/mailSettings.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Email Settings</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="col-12 col-lg-8 col-xl-6">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Paramètres de connexion pour {{ $username }}</h4>
        </div>
        <div class="card-body">
          <ul>
            <li>Nom : choix libre</li>
            <li>Adresse Email : {{ $username }}</li>
            <li>Mot de passe : celui défini à la création</li>
            <li>Type de serveur : POP3</li>
            <li>Port : 995</li>
            <li>Nom du serveur : mail.module-art.fr</li>
            <li>Nom d'utilisateur : {{ $username }}</li>
            <li>Sécurité : SSL/TLS</li>
            <li>Authentification : mot de passe normal</li>
            <li>SMTP : celui fourni par votre FAI (exemples : <a href="https://www.free.fr/assistance/2406.html" target="_blank">Free</a> - <a href="https://assistance.orange.fr/mobile-tablette/tous-les-mobiles-et-tablettes/installer-et-utiliser/utiliser-internet-mail-et-cloud/mail/l-application-mail-orange/parametrer-et-configurer/mail-configurer-les-serveurs-sortants-et-entrants-des-principaux-comptes-mails_47992-48856#onglet2" target="_blank">Orange</a>)</li>
            <li>Si une exception de sécurité est demandée, accepter</li>
          </ul>
          <div class="row justify-content-between px-3">
            {!! link_to_route('mail.create', 'Ajouter un email', [], ['class' => 'btn btn-info']) !!}
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
          <div class="card-footer d-flex justify-content-end mt-2">
            <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
          </div>
        </div>{{--card-body--}}
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/lists.js"></script>
@endsection

resources/views/common/back/pageIndex.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Pages</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Liste des pages</h3>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Titre</th>
                <th>Titre court</th>
                <th>Place au menu</th>
                <th>Publiée</th>
                <th></th>{{--voir--}}
                <th></th>{{--modifier--}}
                <th></th>{{--supprimer--}}
              </tr>
            </thead>
            <tbody>
              @foreach ($pages as $page)
                <tr>
                  <td class="text-primary"><strong>{!! $page->title !!}</strong></td>
                  <td class="text-primary"><strong>{!! $page->menu_title !!}</strong></td>
                  <td class="text-primary">{!! $page->place ? $page->place : 'Hors menu' !!}</td>
                  <td data-toggle="publication" data-page_id="{{ $page->id }}">
                    {!! $page->publie ? '<span class="published"><i class="far fa-check-circle"></i></span>' : '<span class="unpublished"><i class="far fa-times-circle"></i></span>' !!}
                  </td>
                  <td>
                    <a class="btn btn-sm btn-success" href="{{ route('back_page.show', [$page->slug]) }}"><i class="far fa-eye"></i><span class="sr-only">voir</span></a>

                  </td>
                  <td>
                    <a href="{{ route('page.edit', $page->id) }}" class="btn btn-sm btn-warning" title="Modifier" ><i class="far fa-edit"></i><span class="sr-only"> Modifier</span></a>
                  </td>
                  <td>
                    <form method="POST" action="{{ route('page.destroy', $page->id) }}" accept-charset="UTF-8">
                      <input name="_method" type="hidden" value="DELETE">
                      <input name="_token" type="hidden" value="{{ csrf_token() }}">
                    
                      <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Vraiment supprimer cette page et tous les contenus associés ?')"><i class="fas fa-trash-alt"></i><span class="sr-only"> Supprimer</span></button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          {!! $pages->links() !!}
          <div class="row justify-content-between px-3">
            <a href="{{ route('page.create') }}" class="btn btn-info">Ajouter une page</a>
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
          <div class="card-footer d-flex justify-content-end mt-2">
            <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
          </div>
        </div>{{--card-body--}}
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  {{--jquery-ui and tinymce not used but called to avoid reference error--}}
  <script src="/tools/jquery_ui/jquery-ui.min.js"></script>
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/admin.js"></script>
  <script src="/js/lists.js"></script>
@endsection

resources/views/common/back/partial_drag.blade.php
<!DOCTYPE html>
<html>
  <body>

    <?php
      switch ($rubrique->cols) {
        case 1:
          $cols = '';
          break;
        case 2:
          $cols = ' col-md-6';
          break;
        case 3:
          $cols = ' col-md-6 col-lg-4';
          break;
      }
      $order= $rubrique->ascendant ? 'asc' : 'desc'; 
    ?>
    <div class="row" id="drag-mode" data-id="{{ $id_rubrique }}" >

      @include('common.back.inc.menu_rubrique')

      @foreach($rubrique->blocs()->orderBy('place', $order)->get() as $y => $bloc)
        @if($bloc->type == 'large')
          <div class="col-12 large-bloc">
            <div class="dropy" draggable="true" data-position='{{ $y+1 }}' data-place="{!! $bloc->place !!}">
              <div class="upper"></div>
              {!! $bloc->contenu !!}
            </div>
          </div>
        @else
          <div class="col-12{{ $cols }}">
            <div class="dropy" draggable="true" data-position='{{ $y+1 }}' data-place="{!! $bloc->place !!}">
              <div class="upper"></div>
              {!! $bloc->contenu !!}
            </div>
          </div>
        @endif
      @endforeach

    </div><!--row-->
      
  </body>
</html>

resources/views/common/back/typeIndex.blade.php
@extends('themes.'.config('modules.theme').'.template')

@section('title')
  <title>Types de contenu</title>
  <link href="/css/admin.css" rel="stylesheet">
@endsection

@section('sidebar')
  @include('common.back.inc.sidebar')
@endsection

@section('menu')
  @include('themes.'.config('modules.theme').'.menu')
@endsection

@section('contenu')

  <section class='row center-card'>
    <div class="">
      @if(session()->has('info'))
        <div class="alert alert-success alert-dismissible">{!! session('info') !!}</div>
      @endif
      @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible">{!! session('error') !!}</div>
      @endif
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Liste des types de contenu</h3>
        </div>
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Type</th>
                <th>Champs</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              @foreach ($types as $type)
                <tr>
                  <td class="text-primary"><strong>{!! $type->content_type !!}</strong></td>
                  <td class="text-primary"><strong>{!! $type->champs !!}</strong></td>
                  <td>
                    @auth
                      <a href="{{ route('type.insertedIndex', $type->id) }}" class="btn btn-success" title="Lister"><i class="fas fa-list-ul"></i></i><span class="sr-only"> Lister</span></a>
                    @endauth
                  </td>
                  <td>
                    <a href="{{ route('type.edit', $type->id) }}" class="btn btn-warning" title="Modifier" ><i class="far fa-edit"></i><span class="sr-only"> Modifier</span></a>
                  </td>
                  <td>
                    <form method="POST" action="{{ route('type.destroy', $type->id) }}" accept-charset="UTF-8">
                      <input name="_method" type="hidden" value="DELETE">
                      <input name="_token" type="hidden" value="{{ csrf_token() }}">
                      <button type="submit" class="btn btn-danger" onclick="return confirm('Vraiment supprimer ce type et tous les contenus associés ?')"><i class="fas fa-trash-alt"></i><span class="sr-only"> Supprimer</span></button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          {!! $types->links() !!}
          <div class="row justify-content-between px-3">
            <a href="{{ route('type.create') }}" class="btn btn-info">Ajouter un type de contenu</a>
            <a href="javascript:history.back()" class="btn btn-primary">
              <i class="fas fa-redo"></i> Retour
            </a>
          </div>
        </div>
        <div class="card-footer d-flex justify-content-end">
          <a class="btn btn-primary btn-sm" href="{{ route('page.home') }}"><i class="fa fa-redo"></i> retour à l'accueil</a>
        </div>
      </div>
    </div>
  </section>
@endsection

@section('scripts')
  <script src="/js/tinymce/tinymce.min.js"></script>
  <script src="/js/tempus-dominus/moment-with-locales.min.js"></script>
  <script src="/js/tempus-dominus/tempusdominus-bootstrap-4.min.js"></script>
  <script src="/js/admin.js"></script>
@endsection